In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd 
import cv2#bgr formatında okur
from matplotlib import pyplot as plt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:

img = cv2.imread("/lena.png",cv2.IMREAD_COLOR)
print(img)
"""
countx=0
county=0
for i in img:
  countx+=1
  for j in i:
    county+=1

    kırmızı değerleri almak için kırmızı kırmızı al diğerleri sıfır
    etc
"""

None


'\ncountx=0\ncounty=0\nfor i in img:\n  countx+=1\n  for j in i:\n    county+=1\n\n    kırmızı değerleri almak için kırmızı kırmızı al diğerleri sıfır\n    etc\n'

In [ ]:
#plt.imshow(img)

In [ ]:
#from _typeshed import StrOrLiteralStr
# 1.3. sütun yer değiştir
"""
result = []
for i in img:
  for j in i:
    temp=[]
    temp.append(j[2])
    temp.append(j[1])
    temp.append(j[0])
    result.append(temp)
"""
"""#array to image
from PIL import Image as im
data = im.fromarray(np.array(result))
print(data)"""
#plt.imshow(result)

"""
goruntuyu sen sec
iki görüntü var bu iki görüntünün pixel değerleri birbiriyle eşit mi

"""

sag = cv2.imread("/content/lena.png",cv2.IMREAD_COLOR)

sol = cv2.imread("/content/lena.png",cv2.IMREAD_COLOR)
yuzde =0
x=0
for ii in sag:
  y=0
  for jj in ii:
    if jj[0]==sol[x,y][0] and jj[1]==sol[x,y][1] and jj[2] ==sol[x,y][2]:
      yuzde+=1
    y+=1
  x=x+1
print(f"iki görüntü birbirine %{(yuzde*100) /(x*y)} oranında benzemektedir.")


iki görüntü birbirine %37.22953796386719 oranında benzemektedir.


In [ ]:
"""iki görüntü arasındaki benzerlik oranı"""
#import cv2
from cv2 import imread,IMREAD_COLOR
p1 = imread("/content/p1.png",IMREAD_COLOR)
p2 = imread("/content/p2.png",IMREAD_COLOR)

percent = 0
for i in range(len(p1)):
  for j in range(len(p1[0])):
    if p1[i,j][0] == p2[i,j][0] and p1[i,j][1] == p2[i,j][1] and p1[i,j][2] == p2[i,j][2]:
      percent +=1
print(f"iki görüntü birbirine %{(percent*100) /((i+1)*(j+1))} oranında benzemektedir.")


iki görüntü birbirine %100.0 oranında benzemektedir.


In [18]:
#TODO: create a function for changing filter
from typing import Reversible
from cv2 import imread,IMREAD_GRAYSCALE
from numpy import asarray
"""
applying filter to a given image
"""


#default filter
filter = [
[-1, 0, 1],
[-1, 0, 1],
[-1, 0, 1]
]

def change_filter(filtername):
  global filter
  """
  https://www.codingame.com/playgrounds/2524/basic-image-manipulation/filtering
  Sharpening
  The details of an image can be emphasized by using a high-pass filter:
  In this kernel, the pixel is boosted when the neighbor pixels are different.
  filter:
  a b c    a is main ref 
  d e f
  g h i
  :filter
  """
  if filtername == "Sharpening":
    filter = [
    [0, -0.5, 0],
    [-0.5, 3, -0.5],
    [0, -0.5, 0]
    ]
  elif filtername == "Convolution":
    filter = [
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
    ]

change_filter("Convolution")
#get image as gray scale
img = imread("/content/img.png",IMREAD_GRAYSCALE)
#creating filtered_img array
filtered_img = []
for i in range(0,len(img)-3):
  temp = []
  for j in range(0,len(img[0])-3):
    temp.append(0)
  filtered_img.append(temp)


#convert all variables to array
img = asarray(img)
filter = asarray(filter)
filtered_img = asarray(filtered_img)

#apply filter to matrix
for i in range(0,len(img)-len(filter),1):
  for j in range(0,len(img[0])-len(filter[0]),1):
    # filtered_img array = a*f(0,0) + b*f(0,1) + c*f(0,2) + d*f(1,0) ... + i*f(2,2)
    filtered_img[i,j] = img[i,j]*filter[0,0] + img[i,j+1]*filter[0,1] + img[i,j+2]*filter[0,2] + img[i+1,j]*filter[1,0] + img[i+1,j+1]*filter[1,1] + img[i+1,j+2]*filter[1,2] + img[i+2,j]*filter[2,0] + img[i+2,j+1]*filter[2,1] + img[i+2,j+2]*filter[2,2]
print("#####################################")
print("normal image".title())
print(img)
print("#####################################")
print("filtered image".title())
print(filtered_img)
print("#####################################")

#apply pooling to filtered image
#https://paperswithcode.com/method/average-pooling
"""
pool:
a b
c d
:pool
avg_pooled_array.append(avg([a,b,c,d]))
"""
avg_pooled_array = []
max_pooled_array = []
for i in range(0,len(filtered_img)-2,2):
  temp_for_max_pool = []
  for j in range(0,len(filtered_img)-2,2):
    try:
        avg_pooled_array.append(
            (filtered_img[i,j] + filtered_img[i,j+1] + filtered_img[i+1,j] + filtered_img[i+1,j+1])/4
        )
        temp_for_max_pool.append(filtered_img[i,j])
        temp_for_max_pool.append(filtered_img[i,j+1])
        temp_for_max_pool.append(filtered_img[i+1,j])
        temp_for_max_pool.append(filtered_img[i+1,j+1])
        max_pooled_array.append(max(temp_for_max_pool))
    except:
      continue
print("average pooled array".title())
print(avg_pooled_array)
print("#####################################")
print("Max Pooled Array".title())
print(max_pooled_array)
print("#####################################")

#####################################
Normal Image
[[169 169 168 ... 175 162 138]
 [169 169 168 ... 175 162 138]
 [169 169 168 ... 175 162 138]
 ...
 [ 53  53  59 ... 115 112 114]
 [ 53  53  64 ... 117 118 122]
 [ 53  53  64 ... 117 118 122]]
#####################################
Filtered Image
[[ -3  -6   3 ...  15   0 -48]
 [ -3  -6   3 ...  15   0 -48]
 [ -3  -6   3 ...  15   0 -48]
 ...
 [  3   0   7 ...  41  34  -2]
 [  4   4   9 ...  35  28  -2]
 [ 20  17   4 ...  31  20  -2]]
#####################################
Average Pooled Array
[-4.5, -3.0, 6.0, 0.0, -1.5, -6.0, -6.0, -1.5, 10.5, -12.0, 1.5, -3.0, -1.5, 1.5, 0.0, 3.0, 4.5, 13.5, 1.5, 9.0, 6.0, 12.0, -4.5, 1.5, -3.0, -9.0, -15.0, -33.0, -7.5, -57.0, -42.0, -37.5, -16.5, -3.0, 18.0, 4.5, 10.5, 4.5, 9.0, 1.5, -6.0, 0.0, 4.5, -1.5, 0.0, 7.5, -6.0, 1.5, -1.5, -10.5, 9.0, 6.0, 12.0, 6.0, 13.5, -4.5, 7.5, 4.5, 1.5, 12.0, -3.0, 0.0, 15.0, -1.5, 3.0, -7.5, 0.0, 12.0, -3.0, -1.5, -7.5, 3.0, -7.5, 7.5, -3.0, 0.0, -3.0, 15.0, 0.0, -4.